# Generated by Django 4.1.7 on 2023-03-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="product",
            new_name="products",
        ),
    ]
